apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd-test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/rohit-mundayadan/TestArgoCD.git
      revision: main
      files:
      - path: "helm-chart-2/Chart.yaml"
  template:
    metadata:
      name: argo-cd-test
    spec:
      project: default
      source:
        repoURL: https://github.com/rohit-mundayadan/TestArgoCD.git
        targetRevision: main
        path: helm-chart
        helm:
          valueFiles:
          - values.yaml
          parameters:
          - name: image.tag
            value: '{{appVersion}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
